print("ejercicio 1")
lista = [324,367,876, 8,9,9045,777, 9,456,34,65]
print("lista original:", lista)
lista.sort()
print("lista ordenada:", lista)
lista.reverse()
print("lista ordenada al revés:", lista)
print("número de elementos 9: ", lista.count(9))
print("número de elementos 777: ", lista.count(777))
print("")
print("ejercicio 2")
lista = [324,367,876, 8,9,9045,777, 9,456,34,65]
print("lista original:", lista)
listaextend = [1,5,87,45]
lista.extend(listaextend)
print("lista despues de extend: ", lista)
lista.sort(reverse=True)
print("lista ordenada al reves: ", lista)
lista.clear()
print("lista despues de clear: ", lista)
print("")
print("ejercicio 3")
lista = [324,367,876, 8,9,9045,777, 9,456,34,65]
print("lista original:", lista)
lista.append(54)
lista.append(876)
print("lista despues de usar append:", lista)
lista.insert(4, 111)
lista.insert(8, 683)
print("lista despues de usar insert:", lista)
lista.sort()
print("lista ordenada:", lista)
lista.remove(9)
print("lista despues de remove:", lista)
numerodevuelto = lista.pop()
print("valor devuelto por pop:", numerodevuelto)
print("lista despues de pop sin parametro:", lista)
numerodevuelto = lista.pop(3)
print("valor devuelto por pop:", numerodevuelto)
print("lista despues de pop(3):", lista)